title: Ange's Time Squared
author: Ange Louis
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  From Brooklyn to Queens to Manhattan to the Bronx to last (and least ;) Staten Island heare about all the cool adventures possible in New York

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
